import httpx
from llama_index.llms.openai_like import OpenAILike

from config import LLAMA_MODEL, LLAMA_SERVER_HOST, LLAMA_SERVER_PORT

_LLAMA_SERVER_BASE = f"http://{LLAMA_SERVER_HOST}:{LLAMA_SERVER_PORT}/v1"
_LLAMA_SERVER_HEALTH = f"http://{LLAMA_SERVER_HOST}:{LLAMA_SERVER_PORT}/health"

_REFINE_PROMPT = """\
You are a technical review assistant.

The following response was generated by another model:

ORIGINAL RESPONSE:
{original_response}

CONTEXT USED:
{context}

Your task:
1. Remove any chain-of-thought reasoning or exposed thinking tokens.
2. Improve clarity and conciseness.
3. Maintain full technical accuracy — do not invent information.
4. Reply only with the refined version, no additional commentary.

REFINED RESPONSE:"""


def _is_llama_server_up() -> bool:
    try:
        r = httpx.get(_LLAMA_SERVER_HEALTH, timeout=2.0)
        return r.status_code == 200
    except Exception:
        return False


def refinar(original_response: str, context: str) -> str:
    if not _is_llama_server_up():
        return original_response
    llm = OpenAILike(
        model=LLAMA_MODEL,
        api_base=_LLAMA_SERVER_BASE,
        api_key="not-needed",
        is_chat_model=True,
        request_timeout=60.0,
    )
    prompt = _REFINE_PROMPT.format(
        original_response=original_response,
        context=context,
    )
    return str(llm.complete(prompt))
